### ISSUE TITLE
in website sharing, allow adding of whole site via select folder

### ISSUE THREAD

**Issue by n8fr8** [onionshare/onionshare-ios#6] opened 2022-03-22 14:09 UTC
1. use an iOS app to make a local website
2. store in local iOS "files" app filesystem
3. use onionshare to share a website
4. select folder to add the whole website (instead of individual files)

**Comment by tladesignz** [comment] 2022-03-30 15:24
Duplicate of #3

**Comment by tladesignz** [comment] 2022-03-30 15:32
Implemented in

https://github.com/tladesignz/AdParticipesCumCepis/commit/1de8524e4dda41344bbfca047cdfefee426c3c79
https://github.com/tladesignz/AdParticipesCumCepis/commit/53b6c9794661eb34e408c00944f49faee24fd4f1

**Closed by tladesignz** 2022-03-30 15:32 UTC
